apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student42/ratings
maintainers:
  - name: student42
    email: devop042@mail.kmutt.ac.th
sources:
  - https://github.com/nattima0912/bookinfo-ratings